/**
 * Agent Types
 *
 * Types for the Knowledge Agent framework.
 */

export type AgentId = 'archivist' | 'researcher' | 'writer';

export interface Agent {
  id: AgentId;
  name: string;
  description: string;
  icon: string;
  capabilities: AgentCapability[];
  /** Whether agent is enabled by user */
  enabled: boolean;
  /** Schedule for automatic runs (cron-like string or null for manual only) */
  schedule: string | null;
  /** Permissions required */
  permissions: AgentPermission[];
}

export interface AgentCapability {
  id: string;
  name: string;
  description: string;
  /** Whether this capability is enabled */
  enabled: boolean;
}

export type AgentPermission =
  | 'read_notes'
  | 'write_notes'
  | 'create_notes'
  | 'delete_notes'
  | 'use_ai'
  | 'web_search';

export type AgentTaskStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

export interface AgentTask {
  id: string;
  agentId: AgentId;
  capabilityId: string;
  status: AgentTaskStatus;
  /** Input data for the task */
  input: Record<string, unknown>;
  /** Output/result of the task */
  result?: AgentTaskResult;
  /** Error message if failed */
  error?: string;
  /** Progress 0-100 */
  progress: number;
  createdAt: Date;
  startedAt?: Date;
  completedAt?: Date;
}

export interface AgentTaskResult {
  /** Suggestions generated by the agent */
  suggestions?: AgentSuggestion[];
  /** Notes created or modified */
  affectedNoteIds?: string[];
  /** Summary of what was done */
  summary: string;
  /** Detailed log */
  log?: string[];
}

export interface AgentSuggestion {
  id: string;
  agentId: AgentId;
  type: SuggestionType;
  title: string;
  description: string;
  /** Data needed to apply the suggestion */
  payload: Record<string, unknown>;
  /** Priority 1-5 (1 = highest) */
  priority: number;
  /** Whether user has reviewed this suggestion */
  reviewed: boolean;
  /** Whether user applied this suggestion */
  applied: boolean;
  /** Whether user dismissed this suggestion */
  dismissed: boolean;
  createdAt: Date;
}

export type SuggestionType =
  | 'connect_notes' // Link two notes together
  | 'merge_notes' // Combine duplicate notes
  | 'create_note' // Create a new note
  | 'add_tags' // Add tags to note
  | 'remove_duplicate' // Remove duplicate content
  | 'knowledge_gap' // Missing information detected
  | 'contradiction' // Conflicting information found
  | 'briefing' // Generated briefing/summary
  | 'research_update'; // New information found

export interface AgentConfig {
  /** Maximum API calls per day */
  dailyBudget: number;
  /** Current API calls used today */
  dailyUsed: number;
  /** Last reset date */
  lastResetDate: string;
  /** Whether to run agents in background */
  backgroundEnabled: boolean;
  /** Idle time before running background tasks (ms) */
  idleThreshold: number;
}
